package interfaz;
import dominio.*;

//Joaquin Hernandez (257620)
//Alfonso Saizar (305968)


public class IngresoEntrevista extends javax.swing.JFrame {
    private Sistema sistema;
    /**
     * Creates new form IngresoEntrevista
     */
    public IngresoEntrevista() {
        initComponents();
    }
    public IngresoEntrevista(Sistema unSistema) {
        this.sistema = unSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresoEntrevistaTitulo = new javax.swing.JLabel();
        listaEvaluador = new javax.swing.JScrollPane();
        listEvaluador = new javax.swing.JList();
        listaPostulante = new javax.swing.JScrollPane();
        listPostulante = new javax.swing.JList();
        lblEvaluador = new javax.swing.JLabel();
        lblPostulante = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textComentarios = new javax.swing.JTextArea();
        lblPuntaje = new javax.swing.JLabel();
        textPuntaje = new javax.swing.JTextField();
        lblComentarios = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblIngresoEntrevistaTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblIngresoEntrevistaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngresoEntrevistaTitulo.setText("Ingreso de entrevista");
        getContentPane().add(lblIngresoEntrevistaTitulo);
        lblIngresoEntrevistaTitulo.setBounds(6, 6, 478, 30);

        listEvaluador.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listEvaluador.setToolTipText("");
        listEvaluador.setMaximumSize(new java.awt.Dimension(46, 90));
        listEvaluador.setPreferredSize(new java.awt.Dimension(46, 90));
        listaEvaluador.setViewportView(listEvaluador);

        getContentPane().add(listaEvaluador);
        listaEvaluador.setBounds(46, 76, 191, 100);

        listPostulante.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPostulante.setMaximumSize(new java.awt.Dimension(46, 90));
        listaPostulante.setViewportView(listPostulante);

        getContentPane().add(listaPostulante);
        listaPostulante.setBounds(265, 76, 180, 100);

        lblEvaluador.setText("Evaluador");
        getContentPane().add(lblEvaluador);
        lblEvaluador.setBounds(46, 54, 180, 16);

        lblPostulante.setText("Postulante");
        getContentPane().add(lblPostulante);
        lblPostulante.setBounds(265, 54, 180, 16);

        textComentarios.setColumns(20);
        textComentarios.setRows(5);
        jScrollPane3.setViewportView(textComentarios);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(46, 243, 399, 86);

        lblPuntaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPuntaje.setText("Puntaje de entrevista: (0-100)");
        getContentPane().add(lblPuntaje);
        lblPuntaje.setBounds(46, 197, 191, 16);
        getContentPane().add(textPuntaje);
        textPuntaje.setBounds(265, 194, 180, 22);

        lblComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComentarios.setText("Comentarios:");
        getContentPane().add(lblComentarios);
        lblComentarios.setBounds(46, 222, 399, 16);

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(120, 25));
        btnCancelar.setMinimumSize(new java.awt.Dimension(120, 25));
        btnCancelar.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(46, 347, 120, 25);

        btnRegistrar.setText("Registrar");
        btnRegistrar.setMaximumSize(new java.awt.Dimension(120, 25));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(120, 25));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(325, 347, 120, 25);

        setSize(new java.awt.Dimension(504, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoEntrevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoEntrevista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblEvaluador;
    private javax.swing.JLabel lblIngresoEntrevistaTitulo;
    private javax.swing.JLabel lblPostulante;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JList listEvaluador;
    private javax.swing.JList listPostulante;
    private javax.swing.JScrollPane listaEvaluador;
    private javax.swing.JScrollPane listaPostulante;
    private javax.swing.JTextArea textComentarios;
    private javax.swing.JTextField textPuntaje;
    // End of variables declaration//GEN-END:variables
}
