package interfaz;

import dominio.*;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

//Joaquin Hernandez (257620)
//Alfonso Saizar (305968)

public class Menu extends javax.swing.JFrame implements Serializable {
    private Sistema sistema;
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }
    public Menu(Sistema unSistema) {
        this.sistema = unSistema;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuTitulo = new javax.swing.JLabel();
        btnRegistroTematica = new javax.swing.JToggleButton();
        btnAltaPostulante = new javax.swing.JToggleButton();
        btnBajaPostulante = new javax.swing.JToggleButton();
        btnRegistroEvaluador = new javax.swing.JToggleButton();
        btnIngresoEntrevista = new javax.swing.JToggleButton();
        btnRegistroPuesto = new javax.swing.JToggleButton();
        btnConsultaPuesto = new javax.swing.JToggleButton();
        btnHistoriaPostulante = new javax.swing.JToggleButton();
        btnConsultaTematica = new javax.swing.JToggleButton();
        btnFin = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        lblMenuTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblMenuTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuTitulo.setText("Gestión de personal");
        getContentPane().add(lblMenuTitulo);
        lblMenuTitulo.setBounds(6, 17, 486, 30);

        btnRegistroTematica.setText("Registro de temática");
        btnRegistroTematica.setMaximumSize(new java.awt.Dimension(150, 25));
        btnRegistroTematica.setMinimumSize(new java.awt.Dimension(150, 25));
        btnRegistroTematica.setPreferredSize(new java.awt.Dimension(150, 25));
        btnRegistroTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroTematicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroTematica);
        btnRegistroTematica.setBounds(80, 87, 150, 25);

        btnAltaPostulante.setText("Alta de postulante");
        btnAltaPostulante.setMaximumSize(new java.awt.Dimension(150, 25));
        btnAltaPostulante.setMinimumSize(new java.awt.Dimension(150, 25));
        btnAltaPostulante.setPreferredSize(new java.awt.Dimension(150, 25));
        btnAltaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaPostulanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltaPostulante);
        btnAltaPostulante.setBounds(80, 142, 150, 25);

        btnBajaPostulante.setText("Baja de postulante");
        btnBajaPostulante.setMaximumSize(new java.awt.Dimension(150, 25));
        btnBajaPostulante.setMinimumSize(new java.awt.Dimension(150, 25));
        btnBajaPostulante.setPreferredSize(new java.awt.Dimension(150, 25));
        btnBajaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaPostulanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnBajaPostulante);
        btnBajaPostulante.setBounds(268, 142, 150, 25);

        btnRegistroEvaluador.setText("Registro de evaluador");
        btnRegistroEvaluador.setMaximumSize(new java.awt.Dimension(150, 25));
        btnRegistroEvaluador.setMinimumSize(new java.awt.Dimension(150, 25));
        btnRegistroEvaluador.setPreferredSize(new java.awt.Dimension(150, 25));
        btnRegistroEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEvaluadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroEvaluador);
        btnRegistroEvaluador.setBounds(80, 197, 150, 25);

        btnIngresoEntrevista.setText("Ingreso de entrevista");
        btnIngresoEntrevista.setMaximumSize(new java.awt.Dimension(150, 25));
        btnIngresoEntrevista.setMinimumSize(new java.awt.Dimension(150, 25));
        btnIngresoEntrevista.setPreferredSize(new java.awt.Dimension(150, 25));
        btnIngresoEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoEntrevistaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresoEntrevista);
        btnIngresoEntrevista.setBounds(268, 197, 150, 25);

        btnRegistroPuesto.setText("Registro de puesto");
        btnRegistroPuesto.setMaximumSize(new java.awt.Dimension(150, 25));
        btnRegistroPuesto.setMinimumSize(new java.awt.Dimension(150, 25));
        btnRegistroPuesto.setPreferredSize(new java.awt.Dimension(150, 25));
        btnRegistroPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPuestoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroPuesto);
        btnRegistroPuesto.setBounds(80, 252, 150, 25);

        btnConsultaPuesto.setText("Consulta para puesto");
        btnConsultaPuesto.setMaximumSize(new java.awt.Dimension(150, 25));
        btnConsultaPuesto.setMinimumSize(new java.awt.Dimension(150, 25));
        btnConsultaPuesto.setPreferredSize(new java.awt.Dimension(150, 25));
        btnConsultaPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaPuestoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaPuesto);
        btnConsultaPuesto.setBounds(268, 252, 150, 25);

        btnHistoriaPostulante.setText("Historia de postulante");
        btnHistoriaPostulante.setMaximumSize(new java.awt.Dimension(150, 25));
        btnHistoriaPostulante.setMinimumSize(new java.awt.Dimension(150, 25));
        btnHistoriaPostulante.setPreferredSize(new java.awt.Dimension(150, 25));
        btnHistoriaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaPostulanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoriaPostulante);
        btnHistoriaPostulante.setBounds(80, 307, 150, 25);

        btnConsultaTematica.setText("Consulta por temática");
        btnConsultaTematica.setMaximumSize(new java.awt.Dimension(150, 25));
        btnConsultaTematica.setMinimumSize(new java.awt.Dimension(150, 25));
        btnConsultaTematica.setPreferredSize(new java.awt.Dimension(150, 25));
        btnConsultaTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaTematicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaTematica);
        btnConsultaTematica.setBounds(268, 87, 150, 25);

        btnFin.setText("Fin");
        btnFin.setMaximumSize(new java.awt.Dimension(150, 25));
        btnFin.setMinimumSize(new java.awt.Dimension(150, 25));
        btnFin.setPreferredSize(new java.awt.Dimension(150, 25));
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        getContentPane().add(btnFin);
        btnFin.setBounds(268, 307, 150, 25);

        setSize(new java.awt.Dimension(514, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroTematicaActionPerformed
        // TODO add your handling code here:
        RegistroTematica vent = new RegistroTematica(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnRegistroTematicaActionPerformed

    private void btnConsultaTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaTematicaActionPerformed
        // TODO add your handling code here:
        ConsultaPorTematica vent = new ConsultaPorTematica(sistema);
        vent.setVisible(true);
        
    }//GEN-LAST:event_btnConsultaTematicaActionPerformed

    private void btnAltaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaPostulanteActionPerformed
        // TODO add your handling code here:
        AltaPostulante vent = new AltaPostulante(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnAltaPostulanteActionPerformed

    private void btnBajaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaPostulanteActionPerformed
        // TODO add your handling code here:
        BajaPostulante vent = new BajaPostulante(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnBajaPostulanteActionPerformed

    private void btnRegistroEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEvaluadorActionPerformed
        // TODO add your handling code here:
        RegistroEvaluador vent = new RegistroEvaluador(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnRegistroEvaluadorActionPerformed

    private void btnIngresoEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoEntrevistaActionPerformed
        // TODO add your handling code here:
        IngresoEntrevista vent = new IngresoEntrevista(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnIngresoEntrevistaActionPerformed

    private void btnRegistroPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPuestoActionPerformed
        // TODO add your handling code here:
        RegistroPuesto vent = new RegistroPuesto(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnRegistroPuestoActionPerformed

    private void btnConsultaPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaPuestoActionPerformed
        // TODO add your handling code here:
        ConsultaParaPuesto vent = new ConsultaParaPuesto(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnConsultaPuestoActionPerformed

    private void btnHistoriaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaPostulanteActionPerformed
        // TODO add your handling code here:
        HistoriaPostulante vent = new HistoriaPostulante(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnHistoriaPostulanteActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnFinActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        try {
            ObjectOutputStream out = new
            ObjectOutputStream(
            Files.newOutputStream(Paths.get("datos.ser")));
            out.writeObject(sistema);
            out.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error al guardar el archivo",
            "Error al guardar el archivo", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAltaPostulante;
    private javax.swing.JToggleButton btnBajaPostulante;
    private javax.swing.JToggleButton btnConsultaPuesto;
    private javax.swing.JToggleButton btnConsultaTematica;
    private javax.swing.JToggleButton btnFin;
    private javax.swing.JToggleButton btnHistoriaPostulante;
    private javax.swing.JToggleButton btnIngresoEntrevista;
    private javax.swing.JToggleButton btnRegistroEvaluador;
    private javax.swing.JToggleButton btnRegistroPuesto;
    private javax.swing.JToggleButton btnRegistroTematica;
    private javax.swing.JLabel lblMenuTitulo;
    // End of variables declaration//GEN-END:variables
}
