package interfaz;
import dominio.*;

//Joaquin Hernandez (257620)
//Alfonso Saizar (305968)


public class Menu extends javax.swing.JFrame {
    private Sistema sistema;
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }
    public Menu(Sistema unSistema) {
        this.sistema = unSistema;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuTitulo = new javax.swing.JLabel();
        btnRegistroTematica = new javax.swing.JToggleButton();
        btnAltaPostulante = new javax.swing.JToggleButton();
        btnBajaPostulante = new javax.swing.JToggleButton();
        btnRegistroEvaluador = new javax.swing.JToggleButton();
        btnIngresoEntrevista = new javax.swing.JToggleButton();
        btnRegistroPuesto = new javax.swing.JToggleButton();
        btnConsultaPuesto = new javax.swing.JToggleButton();
        btnHistoriaPostulante = new javax.swing.JToggleButton();
        btnConsultaTematica = new javax.swing.JToggleButton();
        btnFin = new javax.swing.JToggleButton();
        menuMenu = new javax.swing.JMenuBar();
        menuPersonas = new javax.swing.JMenu();
        menuRegEvaluador = new javax.swing.JMenuItem();
        menuAltaPostulante = new javax.swing.JMenuItem();
        menuBajaPostulante = new javax.swing.JMenuItem();
        menuHistoriaPostulante = new javax.swing.JMenuItem();
        menuElementos = new javax.swing.JMenu();
        menuRegistroPuesto = new javax.swing.JMenuItem();
        menuRegistroTema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenuTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblMenuTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuTitulo.setText("Gestión de personal");

        btnRegistroTematica.setText("Registro de temática");
        btnRegistroTematica.setMaximumSize(new java.awt.Dimension(150, 25));
        btnRegistroTematica.setMinimumSize(new java.awt.Dimension(150, 25));
        btnRegistroTematica.setPreferredSize(new java.awt.Dimension(150, 25));
        btnRegistroTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroTematicaActionPerformed(evt);
            }
        });

        btnAltaPostulante.setText("Alta de postulante");
        btnAltaPostulante.setMaximumSize(new java.awt.Dimension(150, 25));
        btnAltaPostulante.setMinimumSize(new java.awt.Dimension(150, 25));
        btnAltaPostulante.setPreferredSize(new java.awt.Dimension(150, 25));
        btnAltaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaPostulanteActionPerformed(evt);
            }
        });

        btnBajaPostulante.setText("Baja de postulante");
        btnBajaPostulante.setMaximumSize(new java.awt.Dimension(150, 25));
        btnBajaPostulante.setMinimumSize(new java.awt.Dimension(150, 25));
        btnBajaPostulante.setPreferredSize(new java.awt.Dimension(150, 25));
        btnBajaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaPostulanteActionPerformed(evt);
            }
        });

        btnRegistroEvaluador.setText("Registro de evaluador");
        btnRegistroEvaluador.setMaximumSize(new java.awt.Dimension(150, 25));
        btnRegistroEvaluador.setMinimumSize(new java.awt.Dimension(150, 25));
        btnRegistroEvaluador.setPreferredSize(new java.awt.Dimension(150, 25));
        btnRegistroEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEvaluadorActionPerformed(evt);
            }
        });

        btnIngresoEntrevista.setText("Ingreso de entrevista");
        btnIngresoEntrevista.setMaximumSize(new java.awt.Dimension(150, 25));
        btnIngresoEntrevista.setMinimumSize(new java.awt.Dimension(150, 25));
        btnIngresoEntrevista.setPreferredSize(new java.awt.Dimension(150, 25));
        btnIngresoEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoEntrevistaActionPerformed(evt);
            }
        });

        btnRegistroPuesto.setText("Registro de puesto");
        btnRegistroPuesto.setMaximumSize(new java.awt.Dimension(150, 25));
        btnRegistroPuesto.setMinimumSize(new java.awt.Dimension(150, 25));
        btnRegistroPuesto.setPreferredSize(new java.awt.Dimension(150, 25));
        btnRegistroPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPuestoActionPerformed(evt);
            }
        });

        btnConsultaPuesto.setText("Consulta para puesto");
        btnConsultaPuesto.setMaximumSize(new java.awt.Dimension(150, 25));
        btnConsultaPuesto.setMinimumSize(new java.awt.Dimension(150, 25));
        btnConsultaPuesto.setPreferredSize(new java.awt.Dimension(150, 25));
        btnConsultaPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaPuestoActionPerformed(evt);
            }
        });

        btnHistoriaPostulante.setText("Historia de postulante");
        btnHistoriaPostulante.setMaximumSize(new java.awt.Dimension(150, 25));
        btnHistoriaPostulante.setMinimumSize(new java.awt.Dimension(150, 25));
        btnHistoriaPostulante.setPreferredSize(new java.awt.Dimension(150, 25));
        btnHistoriaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaPostulanteActionPerformed(evt);
            }
        });

        btnConsultaTematica.setText("Consulta por temática");
        btnConsultaTematica.setMaximumSize(new java.awt.Dimension(150, 25));
        btnConsultaTematica.setMinimumSize(new java.awt.Dimension(150, 25));
        btnConsultaTematica.setPreferredSize(new java.awt.Dimension(150, 25));
        btnConsultaTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaTematicaActionPerformed(evt);
            }
        });

        btnFin.setText("Fin");
        btnFin.setMaximumSize(new java.awt.Dimension(150, 25));
        btnFin.setMinimumSize(new java.awt.Dimension(150, 25));
        btnFin.setPreferredSize(new java.awt.Dimension(150, 25));
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        menuPersonas.setText("Personas");

        menuRegEvaluador.setText("Registro de evaluador");
        menuPersonas.add(menuRegEvaluador);

        menuAltaPostulante.setText("Alta de postulante");
        menuPersonas.add(menuAltaPostulante);

        menuBajaPostulante.setText("Baja de postulante");
        menuBajaPostulante.setToolTipText("");
        menuPersonas.add(menuBajaPostulante);

        menuHistoriaPostulante.setText("Historia de postulante");
        menuPersonas.add(menuHistoriaPostulante);

        menuMenu.add(menuPersonas);

        menuElementos.setText("Elementos");

        menuRegistroPuesto.setText("Registro de puesto");
        menuElementos.add(menuRegistroPuesto);

        menuRegistroTema.setText("Registro de temática");
        menuElementos.add(menuRegistroTema);

        menuMenu.add(menuElementos);

        setJMenuBar(menuMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistroPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnConsultaPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistroTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultaTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHistoriaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAltaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBajaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresoEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMenuTitulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultaTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBajaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresoEntrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultaPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistoriaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(514, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroTematicaActionPerformed
        // TODO add your handling code here:
        RegistroTematica vent = new RegistroTematica(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnRegistroTematicaActionPerformed

    private void btnConsultaTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaTematicaActionPerformed
        // TODO add your handling code here:
//        consultaTematica vent = new consultaTematica(sistema);
//        vent.setVisible(true);
        
    }//GEN-LAST:event_btnConsultaTematicaActionPerformed

    private void btnAltaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaPostulanteActionPerformed
        // TODO add your handling code here:
        AltaPostulante vent = new AltaPostulante(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnAltaPostulanteActionPerformed

    private void btnBajaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaPostulanteActionPerformed
        // TODO add your handling code here:
        BajaPostulante vent = new BajaPostulante(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnBajaPostulanteActionPerformed

    private void btnRegistroEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEvaluadorActionPerformed
        // TODO add your handling code here:
        RegistroEvaluador vent = new RegistroEvaluador(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnRegistroEvaluadorActionPerformed

    private void btnIngresoEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoEntrevistaActionPerformed
        // TODO add your handling code here:
        IngresoEntrevista vent = new IngresoEntrevista(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnIngresoEntrevistaActionPerformed

    private void btnRegistroPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPuestoActionPerformed
        // TODO add your handling code here:
        RegistroPuesto vent = new RegistroPuesto(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnRegistroPuestoActionPerformed

    private void btnConsultaPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaPuestoActionPerformed
        // TODO add your handling code here:
        ConsultaParaPuesto vent = new ConsultaParaPuesto(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnConsultaPuestoActionPerformed

    private void btnHistoriaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaPostulanteActionPerformed
        // TODO add your handling code here:
        HistoriaPostulante vent = new HistoriaPostulante(sistema);
        vent.setVisible(true);
    }//GEN-LAST:event_btnHistoriaPostulanteActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAltaPostulante;
    private javax.swing.JToggleButton btnBajaPostulante;
    private javax.swing.JToggleButton btnConsultaPuesto;
    private javax.swing.JToggleButton btnConsultaTematica;
    private javax.swing.JToggleButton btnFin;
    private javax.swing.JToggleButton btnHistoriaPostulante;
    private javax.swing.JToggleButton btnIngresoEntrevista;
    private javax.swing.JToggleButton btnRegistroEvaluador;
    private javax.swing.JToggleButton btnRegistroPuesto;
    private javax.swing.JToggleButton btnRegistroTematica;
    private javax.swing.JLabel lblMenuTitulo;
    private javax.swing.JMenuItem menuAltaPostulante;
    private javax.swing.JMenuItem menuBajaPostulante;
    private javax.swing.JMenu menuElementos;
    private javax.swing.JMenuItem menuHistoriaPostulante;
    private javax.swing.JMenuBar menuMenu;
    private javax.swing.JMenu menuPersonas;
    private javax.swing.JMenuItem menuRegEvaluador;
    private javax.swing.JMenuItem menuRegistroPuesto;
    private javax.swing.JMenuItem menuRegistroTema;
    // End of variables declaration//GEN-END:variables
}
